### ISSUE TITLE
Django Channels Example issues

### ISSUE THREAD

**Issue by jonatasbaldin** [graphql-python/graphql-ws#8] opened 2018-02-07 22:59 UTC
* Python version: 3.6
* Operating System: OSX Sierra

### Description
When testing the Django Channels examples, I went through some errors:

**1:** `graphql_ws/django_channels.py` file is not on the latest package version. But I downloaded it manually inside the package.

**2:** I was getting the error `"Subscriptions are not allowed. You will need to either use the subscribe function or pass allow_subscriptions=True"`. And, since the `GraphQLView` object does not support the `allow_subscriptions` parameter, I changed it inside the package to `True` (just for testing).

**3.** After that, I was getting the error `Subscription must return Async Iterable or Observable`. Reading [this](https://github.com/graphql-python/graphql-core/issues/149) issue, I decided to add `'MIDDLEWARE: []` into the `GRAPHENE` settings variable.

**4.** After that, I started receiving this error: `'AnonymousObservable' object has no attribute 'errors'`. Then I got a little bit frustrated and stop trying 😅 

Does anyone have a clue why this is happening?

Thanks!

**Comment by nick-lehmann** [comment] 2018-02-08 20:41
I have experienced exactly the same today, but after seeing your issue I have stopped trying already after the second step.

**Comment by jonatasbaldin** [comment] 2018-02-08 22:47
I'm whiling to help, but I don't understand too much about the Observables :(

**Comment by mlugowska** [comment] 2018-02-14 12:06
I've checked that `DjangoDebugMiddleware` returns promise, so it cannot be set together with subscriptions and observables. But `AnonymousObservable' object has no attribute 'errors` still occures even when I added field `errors` to observable. I think that it's graphene bug (?). But I still really need to add subscriptions to my django app (graphene-django, python). Do you have any thoughts how can I do this? I know `graphene-django-subscriptions` lib, but does it really necessery to use serializer class only in case of subscriptions? Please, a little help will be desirable.

**Comment by colanconnon** [comment] 2018-02-19 19:31
@jonatasbaldin which version of channels are you using?

**Comment by fcalo** [comment] 2018-03-16 16:05
Changing the urls.py it's solved
https://github.com/eamigo86/graphene-django-subscriptions/issues/2

**Comment by xDHILEx** [comment] 2018-08-11 23:14
I'm stuck on the AnonymousObserable issue as well. https://github.com/xDHILEx/graphqlwsdjangochannels. @colanconnon I'm using channels 1.1.8

**Comment by ambientlight** [comment] 2019-04-11 10:36
just discovered graphene and though of evaluating state of graphql integration with django.
this might a bit late though:

**For short:**
1. To resolve `Subscriptions are not allowed. You will need to either use the subscribe function or pass allow_subscriptions=True` after navigating the call stack I found we can pass a custom backend to GraphQLView that can custom exc_context parameters.
```py
from graphql.backend import GraphQLCoreBackend
class GraphQLCustomCoreBackend(GraphQLCoreBackend):
    def __init__(self, executor=None):
        # type: (Optional[Any]) -> None
        super().__init__(executor)
        self.execute_params['allow_subscriptions'] = True
```

2. Same way, used `MIDDLEWARE: []` in `GRAPHENE` settings. as OP.
3. To resolve 'AnonymousObservable' object has no attribute 'errors'. a custom can to be defined that would unbox `execution_result` from the Observable. (this is hacky) Using ExtraGraphQLView, AuthenticatedGraphQLView outlined in https://github.com/eamigo86/graphene-django-subscriptions/issues/2 didn't work for me as they just as GraphQLView don't handle observables returned from `execute_graphql_request`
```py
class GraphQLObservableUnboxingView(GraphQLView):
    def execute_graphql_request(
            self, request, data, query, variables, operation_name, show_graphiql=False
    ):
        target_result = None

        def override_target_result(value):
            nonlocal target_result
            target_result = value

        execution_result = super().execute_graphql_request(request, data, query, variables, operation_name, show_graphiql)
        if execution_result:
            if isinstance(execution_result, ObservableBase):
                target = execution_result.subscribe(on_next=lambda value: override_target_result(value))
                target.dispose()

        return target_result
```

So in urls.py it can be:
```
url(r'^graphql', GraphQLObservableUnboxingView.as_view(graphiql=True, backend=GraphQLCustomCoreBackend()))
```

I have not used django channels and just tried reproducing the most possible minimal example so that subscription is possible:

```graphql
subscription{
  subscribeToFoo(id: 1)
}
``` 

```py
from rx import Observable
class Subscription(graphene.ObjectType):
    subscribe_to_foo = graphene.Boolean(id=graphene.Int())
    
    def resolve_subscribe_to_foo(self, args, **kwargs):
        return Observable.of(True)

schema = graphene.Schema(query=Query, subscription=Subscription)
```

also please make sure you are using rxpy 1.6.*

**Comment by phjocoronel2806** [comment] 2019-09-20 15:40
what is it ObservableBase?

**Comment by carlosalvarez91** [comment] 2019-12-01 21:05
@ambientlight  your solution seems to work, however since MIDDLEWARE: [ ], it throws not logged in Error...

**Comment by ambientlight** [comment] 2019-12-18 09:57
@phjocoronel2806: `ObservableBase` is from `rxpy`: https://github.com/ReactiveX/RxPY/blob/release/v1.6.x/rx/core/observablebase.py

@carlosalvarez91: haven't used any middleware with the above test so cannot yet give you any feedback on this.

**Comment by arturataideJobCloud** [comment] 2020-04-17 10:36
@carlosalvarez91 same issue as you.. Did you come up with any solution?

**Comment by arturataide** [comment] 2020-04-17 10:38
@carlosalvarez91 same issue as you.. Did you come up with any solution?

**Comment by carlosalvarez91** [comment] 2020-04-17 11:17
@arturataide I ended up using this: https://github.com/datadvance/DjangoChannelsGraphqlWs

**Comment by SmileyChris** [comment] 2021-03-29 23:11
Django v2+ version now merged to master

**Closed by SmileyChris** 2021-03-29 23:11 UTC

**Comment by MedNabilEssefaihi** [comment] 2021-11-26 15:02
Hello there, 

I am trying to call a subscription from PostMan, but whenever run got is error
`
{
    "errors": [
        {
            "message": "Subscription must return Async Iterable or Observable. Received: <Promise at 0x2940d9c7cd0 rejected with AttributeError(\"'NoneType' object has no attribute 'register_subscription'\")>"
        }
    ],
    "data": null
}`

even when I did the same step as @ambientlight did. I can't find any solution for that any help please!
